config/routes.rb
Rails.application.routes.draw do
  post 'certificate/new', to: 'certificate#new', as: 'new_certificate'
  post 'certificate/revoke', to: 'certificate#revoke', as: 'revoke_certificate'
  get 'certificate/download', to: 'certificate#download', as: 'download_certificate'
  post 'certificate/status', to: 'certificate#status', as: 'certificate_status'

  root to: 'visitors#index'
  devise_for :users, :controllers => { :registrations => 'users/registrations' }
  resources :users
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :certificate_password
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  require 'openssl'
  include CertificateAuthority
  
  def create
    super # continue to devise registration to CREATE user
    create_certificate(resource, resource.certificate_password)
  end

  def update
    super # continue to devise registration to UPDATE user
    update_certificate(current_user, resource, resource.certificate_password)
  end
  
  private
  
  def sign_up_params
    params.require(:user).permit(:uid, :firstname, :lastname, :email, :certificate_password, :password, :password_confirmation)
  end
  
  def account_update_params
    params.require(:user).permit(:uid, :firstname, :lastname, :email, :password, :password_confirmation, :current_password, :certificate_password)
  end
end 

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_only, :except => :show

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
      unless @user == current_user
        redirect_to :back, :alert => "Access denied."
      end
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

  def admin_only
    unless current_user.admin?
      redirect_to :back, :alert => "Access denied."
    end
  end

  def secure_params
    params.require(:user).permit(:role)
  end

end

app/views/users/_user.html.erb
<td>
  <%= link_to user.email, user %>
</td>
<td>
  <%= form_for(user) do |f| %>
    <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
    <%= f.submit 'Change Role', :class => 'button-xs' %>
  <% end %>
</td>
<td>
  <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') unless user == current_user %>
</td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
		<table class="table">
          <tbody>
              <tr>
				Certificates Issued: <%= serial %><br />
				Certificates Revoked: <%= revoked_count %><br />
				Current Serial: <%= serial %><br />
              </tr>
          </tbody>
        </table>
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
UID: <%= @user.uid if @user.uid %><br \>
Firstname: <%= @user.firstname if @user.firstname %><br \>
Lastname: <%= @user.lastname if @user.lastname %><br \>
Email: <%= @user.email if @user.email %><br \>
<br \>
<%= link_to 'Edit account',  edit_user_registration_path%><br \>
<%= link_to 'Download Certificate',  download_certificate_path%><br \>

<br \>
<%= form_tag('/certificate/new') do %>
    <fieldset>
      <p>Generate Certificate</p>
      <div class="form-group">
		  <%= label_tag(:password, "Enter Certificate Password:") %>
		  <%= password_field_tag(:password, "", class: 'form-control') %>
		  <%= submit_tag("Generate") %>
      </div>
    </fieldset>
<% end %>

<br \>
<%= form_tag('/certificate/revoke') do %>
    <fieldset>
      <p>Revoke Certificate</p>
      <div class="form-group">
		  <%= label_tag(:certificate_password, "Enter Certificate Password:") %>
		  <%= password_field_tag(:certificate_password, "", class: 'form-control') %>
		  <%= label_tag(:revoke_reason, "Enter Revocation Reason:") %>
		  <%= select_tag(:revoke_reason, options_for_select([['Unspecified', 0], ['Key Compromise', 1], ['CA Compromise', 2], ['Affiliation Changed', 3], ['Superceded', 4], ['Cessation of Operation', 5], ['Certificate Hold', 6]])) %>
		  <%= submit_tag("Revoke") %>
      </div>
    </fieldset>
<% end %>




<br \>
<%= form_tag('/certificate/status', multipart: true) do %>
    <fieldset>
      <p>Check Certificate Status</p>
      <div class="form-group">
		  <%= file_field_tag 'pkcs12_cert' %>
		  <%= label_tag(:password, "Enter Certificate Password:") %>
		  <%= password_field_tag(:password, "", class: 'form-control') %>
		  <%= submit_tag("Check") %>
      </div>
    </fieldset>
<% end %>